import "@/app/globals.css";
import { Rubik } from "next/font/google";
import ReduxProvider from "@/utils/ReduxProvider";

const fontName = Rubik({ weight: "300", subsets: ["latin"] });

export const metadata = {
  title: "Where to Watch",
  description: "Generated by create blakfy app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en" className={fontName.className}>
        <body>{children}</body>
      </html>
    </ReduxProvider>
  );
}
